// packages/web/finvo/src/components/Header.vue
<template>
    <header class="flex justify-between items-center py-4">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-white-900">{{ title }}</h1>
        </div>
    </header>
</template>

<script lang="ts">
export default {
    props: {
        title: {
            type: String,
            required: true,
        },
    },
};
</script>

// frontend/src/components/Header.jsx
import React from 'react'

function Header(props) {
  return (
    <header className="bg-white shadow">
      <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl tracking-tight font-bold text-gray-900">{props.title}</h1>
      </div>
    </header>
  )
}

export default Header
