// packages/web/finvo/src/components/Header.vue
<template>
    <header class="flex justify-between items-center py-4">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-white-900">{{ title }}</h1>
        </div>
    </header>
</template>

<script lang="ts">
export default {
    props: {
        title: {
            type: String,
            required: true,
        },
    },
};
</script>

// frontend/components/Header.tsx
export default function Header({ title }: { title: string }) {
    return (
        <header className="flex justify-between items-center py-4">
            <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                <h1 className="text-3xl font-bold text-white-900">{title}</h1>
            </div>
        </header>
    )
}
