// frontend/pages/index.tsx
import Loading from "@/components/Loading";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
    const router = useRouter();

    useEffect(() => {
        const token = localStorage.getItem('session');
        if (token) {
            router.push('/dashboard');
        } else {
            router.push('/login');
        }
    }, [router]);

    return <Loading />
}

// packages/web/finvo/src/pages/index.vue
<template>
  <Loading />
</template>

<script setup lang="ts">
import Loading from "@/components/Loading.vue";
import { router } from "@/main";

const token = localStorage.getItem('session');
setInterval(() => {
  if (token) {
    router.push('/dashboard');
  } else {
    router.push('/login')
  }
}, 1000);
</script>
